version: '3.3'

services:
  # nginx - web server
  nginx:
    build:
      context: .
      dockerfile: ./docker-config/nginx/Dockerfile
    env_file: &env
      - ./docker-config/nginx/.env
    links:
      - php
    ports:
      - "8000:80"
    volumes:
#      - cpresources:/var/www/project/app/web/cpresources
      - ./app/public:/var/www/project/app/public:cached
  # php - personal home page
  php:
    build:
      context: .
      dockerfile: ./docker-config/php-dev-craft/Dockerfile
    depends_on:
      - "mariadb"
      - "redis"
    env_file:
      *env
    expose:
      - "9000"
    links:
      - mariadb
      - redis
    volumes:
#      - cpresources:/var/www/project/app/web/cpresources
#      - storage:/var/www/project/app/storage
      - ./app:/var/www/project/app:cached
      - ./app/vendor:/var/www/project/app/vendor:delegated
      - ./app/var/logs:/var/www/project/app/var/logs:delegated
  # mariadb - database
  mariadb:
    build:
      context: .
      dockerfile: ./docker-config/mariadb/Dockerfile
    env_file:
      *env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  # redis - key/value database for caching & php sessions
  redis:
    build:
      context: .
      dockerfile: ./docker-config/redis/Dockerfile
    expose:
      - "6379"
volumes:
  db-data:
#  cpresources:
#  storage:
